<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-S5LVNE2" failures="1" tests="6" name="Test" time="0.28" errors="0" timestamp="2025-02-27T11:51:47 IST">
  <testcase classname="TestNgPackage.TestNGTest2" name="test4" time="0.065">
    <failure type="java.lang.AssertionError" message="expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [3]
at TestNgPackage.TestNGTest2.test4(TestNGTest2.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="TestNgPackage.TestNGTest2" name="test5" time="0.023"/>
  <testcase classname="TestNgPackage.TestNGTest2" name="test6" time="0.004"/>
  <testcase classname="TestNgPackage.TestNGTest" name="test1" time="0.006"/>
  <testcase classname="TestNgPackage.TestNGTest" name="test2" time="0.004"/>
  <testcase classname="TestNgPackage.TestNGTest" name="test3" time="0.008"/>
</testsuite> <!-- Test -->
